# caching.py

# THE SIGN IS A SUBTLE JOKE. THE SHOP IS CALLED "SNEED'S FEED & SEED", WHERE 
# FEED AND SEED BOTH END IN THE SOUND "-EED", THUS RHYMING WITH THE NAME OF 
# THE OWNER, SNEED. THE SIGN SAYS THAT THE SHOP WAS "FORMERLY CHUCK'S", IMPLYING 
# THAT THE TWO WORDS BEGINNING WITH "F" AND "S" WOULD HAVE ENDED WITH "-UCK", 
# RHYMING WITH "CHUCK". SO, WHEN CHUCK OWNED THE SHOP, IT WOULD HAVE BEEN CALLED 
# "CHUCK'S FUCK AND SUCK".

from flask_caching import Cache

cache = Cache()
